# -*- coding: utf-8 -*-
"""Redistribute.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1exPCQzw7m_mW9mjP6al3LDKkuCp_fmzz

利用已標註資料集依指定之比例建立訓練、驗證及測試集清單檔案。

參考範例：【AI_Column】如何以YOLOv3訓練自己的資料集─以小蕃茄為例 
https://omnixri.blogspot.com/2019/11/aicolumnyolov3.html
"""

!git clone https://github.com/OmniXRI/OpenVINO_RealSense_HarvestBot.git #取得小蕃茄影像及標註資料集
!ls

# Commented out IPython magic to ensure Python compatibility.
# %cd OpenVINO_RealSense_HarvestBot
# %cd my_yolo3/
!ls

!rm ./VOC2007/ImageSets/Main/*.txt #刪除訓練、驗證、測試資料集清單（*.txt)

"""依指定比例重新分配資料集，訓練加驗證佔2/3，測試佔1/3，而訓練集佔訓練加驗證佔1/2。即訓練集33%，驗證集33%，測試集34%。"""

import os
import random

trainval_percent = 0.66 #訓練加驗證集佔全部資料集比例
train_percent = 0.5 # 訓練集佔訓練加驗證集比例
xmlfilepath = './VOC2007/Annotations' #標註檔路徑
txtsavepath = './VOC2007/ImageSets/Main' #訓練、驗證、測試清單路徑
total_xml = os.listdir(xmlfilepath)

num=len(total_xml)
list=range(num)
tv=int(num*trainval_percent)
tr=int(tv*train_percent)
trainval= random.sample(list,tv)
train=random.sample(trainval,tr)

ftrainval = open('./VOC2007/ImageSets/Main/trainval.txt', 'w') #指定訓練加驗證集清單檔
ftest = open('./VOC2007/ImageSets/Main/test.txt', 'w') #指定測試資料集清單
ftrain = open('./VOC2007/ImageSets/Main/train.txt', 'w') #指定訓練資料集清單
fval = open('./VOC2007/ImageSets/Main/val.txt', 'w') #指定驗證資料集清單

for i  in list:
    name=total_xml[i][:-4]+'\n'
    if i in trainval:
        ftrainval.write(name)
        if i in train:
            ftrain.write(name)
        else:
            fval.write(name)
    else:
        ftest.write(name)

ftrainval.close()
ftrain.close()
fval.close()
ftest .close()

!ls ./VOC2007/ImageSets/Main -all #檢查是否已順利產生訓練、驗證、測試資料集清單（*.txt)