# -*- coding: utf-8 -*-
"""CheckHW.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b5HlxL7hVtMzaBv3jKX0v_suFPY4KcaL
"""

print("CPU Status:")
!cat /proc/cpuinfo | grep model\ name #檢查CPU資訊

print("\nDisk Status:")
!df -lh #檢查磁碟空間

print("\nRAM Status:")
!free -h #檢查記憶體大小

print("GPU Status:")

import tensorflow as tf

print("TensorFlow Ver.:" + tf.__version__) #檢查TensorFlow版本
tf.test.gpu_device_name() #顯示GPU裝置編號，顯示'/device:GPU:0'表示GPU正常運作

!nvidia-smi #檢查NVIDIA　GPU使用狀態

